repos:
  - repo: local
    hooks:
      - id: spotless
        name: Reformat files
        entry: gradlew
        args:
          - spotlessApply
        language: script
        files: \.(java|kt)$
        pass_filenames: false
